Upgrade eslint to 6.8.0 and eslint plugins and configs to latest
ESlint ^6.6.0 is required by react-scripts.

Old ESlint plugins required eslint up to 5.x.

Now all dependencies are satisfied.

Problems with `npm run lint`:

TypeError: Cannot read property 'body' of null
Occurred while linting /home/jlocker/src/github.com/kiegroup/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/src/@types/leaflet-geosearch.d.ts:20
    at checkForConstructor (/home/jlocker/src/github.com/kiegroup/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/eslint/lib/rules/no-useless-constructor.js:161:42)