Upgrade @typescript-eslint/*
Solves previous lint problem.

New lint problem:

/home/jlocker/src/github.com/kiegroup/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/src/ui/components/RouteMap.tsx
  59:3  error  Do not use "// @ts-ignore" comments because they suppress compilation errors  @typescript-eslint/ban-ts-ignore

/home/jlocker/src/github.com/kiegroup/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/src/websocket/WebSocketClient.test.tsx
  28:3  error  Do not use "// @ts-ignore" comments because they suppress compilation errors  @typescript-eslint/ban-ts-ignore

/home/jlocker/src/github.com/kiegroup/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/cypress/integration/fromLocationsToRoute.js
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: cypress/integration/fromLocationsToRoute.js.
The file must be included in at least one of the projects provided

✖ 3 problems (3 errors, 0 warnings)