Solving
```
Caused by: java.lang.NoSuchMethodError: org.mockito.internal.configuration.MockAnnotationProcessor.processAnnotationForMock(Lorg/mockito/Mock;Ljava/lang/Class;Lorg/mockito/internal/util/Supplier;Ljava/lang/String;)Ljava/lang/Object;
```