[7.59.x] BXMSPROD-1673 spring-webmvc/spring-framework 5.3.18. spring-boot to 2.6.6 (#676)
* BXMSPROD-1673 spring-webmvc/spring-framework 5.3.18. spring-boot to 2.6.6

* Solving

```
Caused by: java.lang.NoSuchMethodError: org.mockito.internal.configuration.MockAnnotationProcessor.processAnnotationForMock(Lorg/mockito/Mock;Ljava/lang/Class;Lorg/mockito/internal/util/Supplier;Ljava/lang/String;)Ljava/lang/Object;
```

* WebSocketConfig setAllowedOrigins to setAllowedOriginPatterns